// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Northwind.DataAccessLayer
{
    using Northwind.DataAccessLayer.Model.Context;
    using Northwind.DataAccessLayer.Model.Interfaces;

    // NewTable
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.22.1.0")]
    public partial class NewTable
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 10)
        public string Desc { get; set; } // Desc (length: 10)
        public int? Value { get; set; } // Value
        public System.DateTime? NewField { get; set; } // NewField

        public NewTable()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
